# Generated by Django 4.0.3 on 2022-12-08 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobilevo',
            name='vehicleSold',
            field=models.BooleanField(default=False),
        ),
    ]
