# Generated by Django 4.0.3 on 2022-12-09 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0002_alter_autotechnician_employee_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceappointment',
            name='cancel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serviceappointment',
            name='finish',
            field=models.BooleanField(default=False),
        ),
    ]
