# Generated by Django 4.0.3 on 2022-12-09 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0003_serviceappointment_cancel_serviceappointment_finish'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobilevo',
            name='dealership_purchase',
            field=models.BooleanField(default=False),
        ),
    ]
