# Generated by Django 4.0.3 on 2022-12-10 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0005_remove_automobilevo_dealership_purchase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceappointment',
            name='date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='serviceappointment',
            name='time',
            field=models.CharField(max_length=10),
        ),
    ]
