# Generated by Django 4.0.3 on 2022-12-11 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0006_alter_serviceappointment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceappointment',
            name='cancel',
        ),
        migrations.RemoveField(
            model_name='serviceappointment',
            name='finish',
        ),
    ]
